"""
Adjusts values for all 2000 census data so it maps to 2010 geography

Input
------
Takes the stdout of `create_census_data.py` as stdin

Arguments
----------
argv[1] : str
    The geography level to create weights for (block-groups or tracts)
argv[2] : str
    The file path to the weights for the given geography 
    generated by `create_00_weights.py`


Outputs
-------
str
    a string of CSV data containing the weights

Example output ():


"""

import sys
import csv
import pandas as pd
from utils_validation import (merge_with_stats, logger)
from utils_census import create_tract_name
from data_constants import NUMERIC_COLS

if __name__ == '__main__':
    # read output from `create_census_data.py` into data frame
    data_df = pd.read_csv(
        sys.stdin,
        dtype={
            'GEOID': 'object',
            'name': 'object',
            'parent-location': 'object'
        })
    # read in weights output from `create_00_weights.py`
    weight_df = pd.read_csv(
        sys.argv[2], dtype={
            'GEOID00': 'object',
            'GEOID10': 'object'
        })

    weight_df = pd.DataFrame(weight_df.groupby(['GEOID00', 'GEOID10'])['weight_2010'].sum()).reset_index()
    weight_df.fillna(0, inplace=True)

    # merge the census data with the weights for each GEOID
    # output_df = weight_df.merge(
    #     data_df, left_on='GEOID00', right_on='GEOID', how='left')
    output_df = merge_with_stats(sys.argv[1]+' weights <- data', weight_df, data_df, left_on='GEOID00', right_on='GEOID', how='left')

    # create data frame with unique GEOID10 and associated name and parent-location
    context_df = output_df[['GEOID10', 'name', 'parent-location']].copy()
    context_df.drop_duplicates(subset=['GEOID10'], inplace=True)

    # multiply all numeric columns by the weight
    output_df[NUMERIC_COLS] = output_df[NUMERIC_COLS].multiply(
        output_df['weight_2010'], axis=0)

    # group all data by GEOIDs / year, and sum values together 
    output_df = pd.DataFrame(
        output_df.groupby(['GEOID10',
                           'year'])[NUMERIC_COLS].sum()).reset_index()
    
    # merge in the name and parent-location for all GEOIDs
    output_df = output_df.merge(context_df, on='GEOID10', how='left')
    output_df['year'] = output_df['year'].astype('int')

    output_df.rename(columns={'GEOID10': 'GEOID'}, inplace=True)

    # format the name for tracts and block groups
    if sys.argv[1] == 'tracts':
        output_df['name'] = output_df['GEOID'].str.slice(5).apply(
            create_tract_name)
    elif sys.argv[1] == 'block-groups':
        output_df['name'] = output_df['GEOID'].str.slice(5, -1).apply(
            create_tract_name) + '.' + output_df['GEOID'].str.slice(-1)
    else:
        raise ValueError('Invalid geography string supplied')

    # output to stdout
    output_df.to_csv(sys.stdout, index=False, quoting=csv.QUOTE_NONNUMERIC)
